### ISSUE TITLE
CM status for Puppet is out of date

### ISSUE THREAD

**Issue by mjbrender** [basho-labs/the-riak-community#53]
I noticed that the compliance level noted in https://github.com/basho-labs/the-riak-community/blob/master/config-mgmt-strategy.md is out of date. Hey @danieldreier, maybe we could synch up and clean this up?

**Comment by danieldreier** [comment]
good idea, thanks for pointing that out.

**Comment by mjbrender** [comment]
Sorry on the merge delay and thanks for this.
