### ISSUE TITLE
List of buckets after upgrading 2.05 -> 2.1 time out

### ISSUE THREAD

**Issue by msinev** [basho-labs/the-riak-community#55]
We are recently start testing Riak as an archive storage. After upgrading 2.05 -> 2.1 we can't list buckets any more. Request times outs  returning nothing. The rest of functionality seems works ok. We are running cluster of two nodes. Both has been upgraded 
We are getting list of buckets using http 

e.g.  wget -T 15 http://88.198.**.**:8098/buckets/?buckets=true
--2015-04-20 16:17:30--  http://88.198.**.**:8098/buckets/?buckets=true
Connecting to 88.198.**.**:8098... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.
....

**Comment by andrewjstone** [comment]
@msinev I'm not seeing a problem locally, but I also did not upgrade. Listing buckets appears to work fine on 2.1. Also, this is not the correct repo to file an issue on. Can you please create an issue on github.com/basho/riak instead.

**Comment by mjbrender** [comment]
Hey @msinev - I'm glad to see your participation! I'm going to close this issue per @andrewjstone's note. You're welcome to make community-wide recommendations as issues here and open up code-specific requests on the appropriate repo.
