### ISSUE TITLE
Giving Webmachine its own GitHub Organization

### ISSUE THREAD

**Issue by mjbrender** [basho-labs/the-riak-community#58]
I'm working on the logistics to get [the Webmachine project](https://github.com/basho/webmachine) its own organization. It would benefit our greater community by passing responsibility of a well-adopted project to a larger organization of people, however informal, to curate. 

Let's discuss how to achieve this. 

One minor blocker is the fact @webmachine is not available for an Organization due to the existence of a user by that name. I've reached out in [this GitHub issue](https://github.com/webmachine/PhpOopTutorial/issues/1) to see if s/he would be kind enough to pass us that name. Either way, **this preferred handle should no prevent us from thinking through next steps.**

Initial thoughts: 

- [x] Establish an Open Source organization for Webmachine on GitHub
- [x] Add trusted users to the organization created above 
- [x] Update the README to explains the new organization (for linking purposes)
- [x] Use the *Transfer Repository* feature of GitHub to move the existing repo from the Basho to the Webmachine org
- [x] Profit :+1: 

Some concerns: 

- [x] What - if any - build concerns are there
- [x] Who Internal to Basho can shepherd our side to make sure Riak still works and stays updated 
- [x] Concerns on impact of the repo migration (a general angst we should explore) 

With that, let's get this discussion going.

**Comment by mjbrender** [comment]
Discussing a little more, it seems a README-only wouldn't work given we'll want to build from it. The Basho org will need to fork Webmachine and whoever acts as shepherd will update from origin. 

I think a custom README is important as well to explain the move. Maybe it will make sense to update the main README anyway and that will cover the conversation.

**Comment by seancribbs** [comment]
@mjbrender In anticipation of this move, @joedevivo established the [https://github.com/wrq](wrq) organization (and we forked webmachine there later).

My main concerns are:

1. Non-Basho stakeholders should have strong input into direction.
2. Basho projects are not broken by changes to the organization's copy (perhaps through a Basho copy, or mutual review of changes).
3. CI should be public (Travis, quickcheck-ci, something else, or any of the above).

**Comment by HMcKelvey** [comment]
Please remember this will take engineering resources and will have to be
prioritized and scheduled. Personally I think it should happen but want to
be clear that it may not be a priority.
Best,
Heather

On Fri, May 29, 2015 at 6:25 AM, Matt Brender <notifications@github.com>
wrote:

> I'm working on the logistics to get the Webmachine project
> <https://github.com/basho/webmachine> its own organization. It would
> benefit our greater community by passing responsibility of a well-adopted
> project to a larger organization of people, however informal, to curate.
>
> Let's discuss how to achieve this.
>
> One minor blocker is the fact @webmachine <https://github.com/webmachine>
> is not available for an Organization due to the existence of a user by that
> name. I've reached out in this GitHub issue
> <https://github.com/webmachine/PhpOopTutorial/issues/1> to see if s/he
> would be kind enough to pass us that name. Either way, *this preferred
> handle should no prevent us from thinking through next steps.*
>
> Initial thoughts:
>
>    -  Establish an Open Source organization for Webmachine on GitHub
>    -  Add trusted users to the organization created above
>    -  Use the *Transfer Repository* feature of GitHub to move the
>    existing repo from the Basho to the Webmachine org
>    -  Create a README-only repo on Basho that explains the new
>    organization (for linking purposes)
>    -  Profit [image: :+1:]
>
> Some concerns:
>
>    -  What to do we - at Basho - do on builders
>    -  Who Internal to Basho can shepherd our side to make sure Riak still
>    works and stays updated
>    -  Concerns on impact of the repo migration (a general angst we should
>    explore)
>
> With that, let's get this discussion going.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/basho-labs/the-riak-community/issues/58>.
>



-- 
Heather McKelvey
VP Engineering
Basho Technologies

**Comment by HMcKelvey** [comment]
I am for this move and the community involvement will drive the priority.

**Comment by jrwest** [comment]
If engineering resources are the concern, would it be better for Basho to
turn over control of the repository to the community and then treat it like
any other 3rd-party dependency in Riak (of which there are many)? If that
was already the plan what other resources are necessary? Shouldn't it just
be moving the repository and changing ownership. Rebar was moved several
times while Riak continued w/o issue or additional effort.

Jordan

**Comment by seancribbs** [comment]
@jrwest Exactly, there is precedent here.

**Comment by HMcKelvey** [comment]
Jordan and Sean,
You are both correct. It is impetus to move webmachine to it's own org.


On Fri, May 29, 2015 at 9:15 AM, Sean Cribbs <notifications@github.com>
wrote:

> @jrwest <https://github.com/jrwest> Exactly, there is precedent here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/basho-labs/the-riak-community/issues/58#issuecomment-106861351>
> .
>



-- 
Heather McKelvey
VP Engineering
Basho Technologies

**Comment by jrwest** [comment]
Great :). If Basho does not feel they can provide the resources I am happy
to make the necessary changes, this weekend or next, and submit all the
pull requests, -- but honestly the review will probably take longer than
having one of the Basho engineers make the change and test it locally.

**Comment by jrwest** [comment]
Also, while we are going through this exercise could we also discuss moving
the lager repository to its own organization as well (this would include
the lager_syslog, etc backends too)? This project is as crucial to the
community as web machine and is used in a large amount of projects. I think
the community would benefit greatly from it having its own official
organization like web machine.

**Comment by mjbrender** [comment]
One step at a time @jrwest - please open another Issue in this repo to discuss doing so. Let's focus on Webmachine right now to start.

@seancribbs the main concerns you outlined are identical to our own. I have the utmost trust you'll help us responsibly pass ownership to a 3rd party. The direction of Webmachine would be based on its core maintainers, some of who may be Basho engineers and some not. It's not about their affiliation with a company - it's about their dedication to the community process. We don't have to go full Apache process on this, but some structure is nice.

@jrwest, I don't anticipate we can safely by the end of the weekend, but we can and will certainly start the process. I'll keep in touch on timing. 

@seancribbs, your domain knowledge in who and what to assure we don't break (too many) things in the process would be lovely.

**Comment by jrwest** [comment]
Happy to open a separate issue if that is the way you would prefer it done
but to be clear I was trying to make it easier, by going through the
process for both of them together, given Basho has already complained about
the amount engineering resources this would take.

As for my offer to do the work, I only mentioned as early as this weekend
since Heather pointed out that priority will be driven by community
involvement.

**Comment by mjbrender** [comment]
@jrwest sounds good. I'm happy to have your expertise here. 

Great news - the user on @webmachine has given up the handle for us. I made an organization and will start working on team membership when I get free time this afternoon. @seancribbs, I plan to make you owner and bow out of the org given that I know 0 about Webmachine :smile:. It's all you. 

Woot, progress!

**Comment by seancribbs** [comment]
@mjbrender Excellent!

**Comment by mjbrender** [comment]
Hey @seancribbs - I've begun to update the organization. I haven't made headway on ensuring migration won't break all the things internally. Let me know if you're aware of internal gotchas that I wouldn't be.

**Comment by seancribbs** [comment]
@mjbrender Immediately after the transfer, you should likely fork back to the "basho" organization to prevent breakages. Aside from putting the appropriate people in the "Owners" team, I can't think of what else needs doing.

**Comment by jaybeeweb** [comment]
Hi Matt,I just have one concern about the name webmachine. I have used it for years in accounts I have on the web - forums, software sites etc - probably much longer than your use on GitHub.. You would not come back sometime in the future and tell me I can't use that name any more there because you have some sort of trademark on it, would you?JeanJean BraithwaiteWeb Design & Development(416) 993-7323http://jaybeeweb.com


-------- Original Message --------
Subject: Re: [the-riak-community] Giving Webmachine its own GitHub
Organization (#58)

**Comment by seancribbs** [comment]
@jaybeeweb The "webmachine" project existed long before Github, at least back to 2009, if not earlier. Here is the first commit imported into Bitbucket by @justinsheehy: https://bitbucket.org/justin/webmachine/commits/e68ae3bcc0908e5d9e26c99dd058c00bb4ca0298 

It was imported to Github some years later when Basho made the switch to git.

**Comment by justinsheehy** [comment]
For the record: the first publicly visible commits to webmachine were on Google Code in March 2008.

Also, trademarks do not cover use of a name in general but rather the use of that name to describe specific goods or services and to distinguish them from similar goods or services provided by another party. I wouldn't be that concerned on this count unless you are making software similar to webmachine.

**Comment by jaybeeweb** [comment]
I've been using this username on my accounts since before 2007 (case in point Sitepoint forums) - I just want assurance that I will not be asked to totally abandon it.Jean BraithwaiteWeb Design & Development(416) 993-7323http://jaybeeweb.com


-------- Original Message --------
Subject: Re: [the-riak-community] Giving Webmachine its own GitHub
Organization (#58)

**Comment by jaybeeweb** [comment]
Thank you.Jean BraithwaiteWeb Design & Development(416) 993-7323http://jaybeeweb.com


-------- Original Message --------
Subject: Re: [the-riak-community] Giving Webmachine its own GitHub
Organization (#58)

**Comment by mjbrender** [comment]
Hey @jaybeeweb - I can assure you that we do not intent to ask you to abandon the name. Your willingness to pass it over on GitHub was kind of you and I have no further expectations on its use. I'm no lawyer and have nothing reassuring to add beyond this point. 

Thanks again for your kindness - there's no reason for proof of lineage.

**Comment by mjbrender** [comment]
Hey @seancribbs - I'm connecting with @jonmeredith tomorrow. You both have been added to the organization as owners and @jrwest is in there as a maintainer. I'm talk through details w/Jon and migrate the main repo over tomorrow if all goes well. From there, :godmode: will be enabled and I'm trusting you'll shepherd in a healthy group of maintainers that can bring the project forward. 

Sound good?

**Comment by kuenishi** [comment]
I want to give a big +1 to this - although webmachine is a core component of Riak CS, we haven't have invested much time on webmachine. I also want to see good different quip in every release.

**Comment by seancribbs** [comment]
@mjbrender We will nurture it well.

**Comment by sdebnath** [comment]
I think this is an excellent idea. A big +1. This will get me motivated to go fix this issue (https://github.com/mochi/mochiweb/issues/146) as well.

**Comment by seancribbs** [comment]
@mjbrender Any progress on transferring the repository?

**Comment by mjbrender** [comment]
@seancribbs planning for EOD today. cc @HMcKelvey @jonmeredith

**Comment by mjbrender** [comment]
I'm glad to see this come to conclusion. Thanks again for your help leading us through it @seancribbs and @jonmeredith.
