### ISSUE TITLE
Delete object fail with riakc_pb_socket

### ISSUE THREAD

**Issue by barcoyou** [basho-labs/the-riak-community#61]
Riak version: Head of master branch
Erlang version: R16B02 

Pid = riakc_pb_socket:start_link("192.168.1.102", 10017).
{ok,<0.1248.0>}
(portal@127.0.0.1)10> riakc_pb_socket:delete(Pid, {<<"snippet">>, <<"5091">>}, <<"19033">>).
** exception exit: {{function_clause,
                        [{gen,call,
                             [{ok,<0.1248.0>},
                              '$gen_call',
                              {req,
                                  {rpbdelreq,<<"5091">>,<<"19033">>,undefined,undefined,
                                      undefined,undefined,undefined,undefined,undefined,undefined,
                                      undefined,undefined,<<"snippet">>},
                                  60000},
                              infinity],
                             [{file,"gen.erl"},{line,149}]},
                         {gen_server,call,3,[{file,"gen_server.erl"},{line,186}]},
                         {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,661}]},
                         {shell,exprs,7,[{file,"shell.erl"},{line,676}]},
                         {shell,eval_exprs,7,[{file,"shell.erl"},{line,631}]},
                         {shell,eval_loop,3,[{file,"shell.erl"},{line,616}]}]},
                    {gen_server,call,
                        [{ok,<0.1248.0>},
                         {req,
                             {rpbdelreq,<<"5091">>,<<"19033">>,undefined,undefined,
                                 undefined,undefined,undefined,undefined,undefined,undefined,
                                 undefined,undefined,<<"snippet">>},
                             60000},
                         infinity]}}
     in function  gen_server:call/3 (gen_server.erl, line 190)

**Comment by mjbrender** [comment]
Hey @barcoyou - excuse the delay. Let's find out what repo this error affects and get it routed over there as soon as we do. I'll post in the Riak S2 repo and keep us posted on this thread.

**Comment by kuenishi** [comment]
This is just mismatch before starting deletion. You should have written like this.

```
{ok, Pid} = riakc_pb_socket:start_link("192.168.1.102", 10017).
```

**Comment by mjbrender** [comment]
Hey @barcoyou - there you go (with thanks to @kuenishi). While you're welcome to post anything you are confident is a bug in GitHub, it may be easier to discuss these over the riak-user mailing list. If you haven't already, [sign up](http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com)! 

Closing.
